project = 'GrandMA2 LUA Reference'
description = 'Command reference for GrandMA2 LUA function'
full_description = [[
This is a reference of all the known LUA commands available on the GrandMA2

This reference is community provided and there is no garuantee of accuracy.
]]
file = {
     'gma.gui.lua',
     'gma.gui.progress.lua',
     'gma.lua',
     'gma.network.lua',
     'gma.show.getobj.lua',
     'gma.show.lua',
     'gma.show.property.lua',
     'gma.timestamp.lua',
     'gma.user.lua'
}
